config/routes.rb
TolkEngine::Engine.routes.draw do

  devise_for :translators, :controllers => { :registrations => 'tolk_engine/custom_devise/registrations', :sessions => 'tolk_engine/custom_devise/sessions'  }, :class_name => 'TolkEngine::Translator', :module => :devise

  resources :translators
  resources :yml_sources
  resources :phrase_database_filler, :only => [:show, :index]
  resources :translations

  resources :locales do
    resources :missing_translations, :only => [:index]
    resources :translations
    resources :translators
    resources :yml_files, :only => [:index]
  end

  resources :phrases do
    resources :translations
  end

  resources :translations_in_line do
    collection do
      put :update
    end
  end

  resources :phrases
  resources :locales

  root :to => 'home#index'

end

app/models/tolk_engine/ability.rb
module TolkEngine
  class Ability
    include CanCan::Ability

    def initialize(translator)
      translator ||= Translator.new # guest translator

      if translator.admin
        can :manage, :all
      else
        can :read, :all

        cannot :read, YmlSource
        cannot :update, Locale
        cannot :create, Locale
        cannot :destroy, Locale
        cannot :read, Translator

        can :update, Translation do |translation|
          translation.locale_id == translator.locale_id
        end
        can :create, :all
      end
    end
  end
end

app/controllers/tolk_engine/application_controller.rb
module TolkEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery
    before_filter :initialize_locales_name

    layout "tolk_engine/layouts/tolk_engine"

    def current_ability
      @current_ability ||= Ability.new(current_translator)
    end

    rescue_from CanCan::AccessDenied do |exception|
      if !translator_signed_in?
        session[:translator_return_to] = request.url
        redirect_to new_translator_session_path, :alert => exception.message
      else
        redirect_to root_url, :alert => exception.message
      end
    end

    def standard_respond_to(class_type)
      respond_to do |format|
        format.html
        format.json { render json: class_type }
      end
    end

    def destroy_respond_to
      respond_to do |format|
        format.html { redirect_to locales_url }
        format.json { head :no_content }
      end
    end

    def create_respond_to(class_type)
      respond_to do |format|
        if class_type.save
          format.html { redirect_to class_type, notice: class_type.class.to_s + ' was successfully created.' }
          format.json { render json: class_type, status: :created, location: class_type }
        else
          fail_respond_to("new", class_type)
        end
      end
    end

    def update_respond_to(class_type, parameters, redirect_path = class_type)
      respond_to do |format|
        if class_type.update_attributes(parameters)
          format.html { redirect_to redirect_path, notice: class_type.class.to_s + ' was successfully updated.' }
          format.json { head :no_content }
        else
          fail_respond_to("edit", class_type)
        end
      end
    end

    def fail_respond_to(type_of_action, class_type)
      format.html { render action: type_of_action }
      format.json { render json: class_type.errors, status: :unprocessable_entity }
    end

    def initialize_locales_name
      @locales_name = {
        'ar' => 'Arabic',
        'bs' => 'Bosnian',
        'bt' => 'Bulgarian',
        'ca' => 'Catalan',
        'cz' => 'Czech',
        'da' => 'Danish',
        'de' => 'German',
        'dsb' => 'Lower Sorbian',
        'el' => 'Greek',
        'en' => 'English',
        'es' => 'Spanish',
        'et' => 'Estonian',
        'fa' => 'Persian',
        'fi' => 'Finnish',
        'fr' => 'French',
        'he' => 'Hebrew',
        'hr' => 'Croatian',
        'hsb' => 'Upper Sorbian',
        'hu' => 'Hungarian',
        'id' => 'Indonesian',
        'is' => 'Icelandic',
        'it' => 'Italian',
        'jp' => 'Japanese',
        'ko' => 'Korean',
        'lo' => 'Lao',
        'lt' => 'Lithuanian',
        'lv' => 'Latvian',
        'mk' => 'Macedonian',
        'nl' => 'Dutch',
        'no' => 'Norwegian',
        'pl' => 'Polish',
        'pt-BR' => 'Portuguese (Brazilian)',
        'pt-PT' => 'Portuguese (Portugal)',
        'ro' => 'Romanian',
        'ru' => 'Russian',
        'se' => 'Swedish',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'sr' => 'Serbian',
        'sw' => 'Swahili',
        'th' => 'Thai',
        'tr' => 'Turkish',
        'uk' => 'Ukrainian',
        'vi' => 'Vietnamese',
        'zh-CN' => 'Chinese (Simplified)',
        'zh-TW' => 'Chinese (Traditional)'
      }

    end

    def create_phrase_translation_table(translations)
      primary_locale = Locale.primary_locale
      first_locale_translations = primary_locale.translations
      translations.inject({}) do |relevant_phrase_text, translation|
        relevant_phrases = first_locale_translations.where(:phrase_id => translation.phrase_id)
        relevant_phrase = relevant_phrases.first
        relevant_phrase_text[translation.phrase_id] = relevant_phrase && relevant_phrase.text
        relevant_phrase_text
      end
    end

    def missing_translation?(locale)
      if !locale.nil?
        current_done_translation = locale.translations.where(:needed_update => 0).count
        phrase_quantity - current_done_translation
      else
        1
      end
    end

    def phrase_quantity
      reference_locale = Locale.primary_locale
      reference_locale.nil? ? 0 : reference_locale.translations.count
    end

  end
end

app/controllers/tolk_engine/custom_devise/registrations_controller.rb
module TolkEngine
  class CustomDevise::RegistrationsController < Devise::RegistrationsController
    layout "tolk_engine/layouts/tolk_engine"

    def new
      @locales = Locale.all
      super
    end

    def create
      @locales = Locale.all
      super
    end
  end
end

app/controllers/tolk_engine/custom_devise/sessions_controller.rb
module TolkEngine
  class CustomDevise::SessionsController < Devise::SessionsController
    layout "tolk_engine/layouts/tolk_engine"

    def new
      @locales = Locale.all
      super
    end

    def create
      @locales = Locale.all
      super
    end
  end
end

app/controllers/tolk_engine/home_controller.rb
module TolkEngine
  class HomeController < TolkEngine::ApplicationController
    protect_from_forgery

    require 'yaml'

     layout "tolk_engine/layouts/tolk_engine"

    def index
      @locales = Locale.all

      if @locales.empty?
        redirect_to tolk_engine.locales_path
      end


      if translator_signed_in?
        @missing_translation = missing_translation?(Locale.find(current_translator.locale.id))
        @ratio = ratio(@missing_translation)
      end
    end

    def ratio(missing_translation)
        primary_keyword_quantity = phrase_quantity
      if primary_keyword_quantity != 0
        ratio = (missing_translation * 100) / primary_keyword_quantity
        ratio = 100 - ratio
        ratio
      else
        ratio = 100
      end
    end

  end
end

app/controllers/tolk_engine/locales_controller.rb
module TolkEngine
  class LocalesController < TolkEngine::ApplicationController

    load_and_authorize_resource :locale, :class => TolkEngine::Locale


    def index
      @missing_translation = {}
      @locales.each do |locale|
        @missing_translation[locale.name] = missing_translation?(locale)
      end
      standard_respond_to(@locales)
    end

    # GET /locales/1
    # GET /locales/1.json
    def show
      standard_respond_to(@locale)
    end

    # GET /locales/new
    # GET /locales/new.json
    def new
      standard_respond_to(@locale)
    end

    # GET /locales/1/edit
    def edit
    end

    # POST /locales
    # POST /locales.json
    def create
      @locale = Locale.new(params[:locale])
      create_respond_to(@locale)
    end

    # PUT /locales/1
    # PUT /locales/1.json
    def update
      update_respond_to(@locale, params[:locale])
    end

    # DELETE /locales/1
    # DELETE /locales/1.json
    def destroy
      @locale.destroy

      destroy_respond_to
    end

    def missing_translation?(locale)
      reference_locale = Locale.primary_locale
      primary_keyword_quantity = reference_locale.translations.count
      current_done_translation = locale.translations.where(:needed_update => 0).count
      primary_keyword_quantity - current_done_translation
    end

  end
end

app/controllers/tolk_engine/phrase_database_filler_controller.rb
module TolkEngine
  class PhraseDatabaseFillerController < TolkEngine::ApplicationController
     layout "tolk_engine/layouts/tolk_engine"
    def show
      @yml_source = YmlSource.find(params[:id])

      @counter = TolkEngine::YmlLoader.load_yaml_source(@yml_source)
    end

    def index
    	YmlSource.find_each do |yml_source|
    		@counter = TolkEngine::YmlLoader.load_yaml_source(yml_source)
    	end
    end
  end
end

app/controllers/tolk_engine/phrases_controller.rb
module TolkEngine
  class PhrasesController < TolkEngine::ApplicationController
    # GET /phrases
    # GET /phrases.json
    layout "tolk_engine/layouts/tolk_engine"
    before_filter :authenticate_translator!
    load_and_authorize_resource :phrase, :class => TolkEngine::Phrase

    def index
      standard_respond_to(@phrase)
    end

    # GET /phrases/1
    # GET /phrases/1.json
    def show
      standard_respond_to(@phrase)
    end

    # GET /phrases/new
    # GET /phrases/new.json
    def new
      @phrase = Phrase.new
      standard_respond_to(@phrase)
    end

    # GET /phrases/1/edit
    def edit
    end

    # POST /phrases
    # POST /phrases.json
    def create
      create_respond_to(@phrase)
    end

    # PUT /phrases/1
    # PUT /phrases/1.json
    def update
      update_respond_to(@phrase, params[:phrase])
    end

    # DELETE /phrases/1
    # DELETE /phrases/1.json
    def destroy
      @phrase.destroy
      destroy_respond_to
    end

  end
end

app/controllers/tolk_engine/sessions_controller.rb
module TolkEngine
  class SessionsController < Devise::SessionsController
    layout "tolk_engine/layouts/tolk_engine"
    def new
      super
    end

    def create
      # add custom create logic here
    end

    def update
      super
    end
  end
end

app/controllers/tolk_engine/translations_controller.rb
module TolkEngine
  class TranslationsController < TolkEngine::ApplicationController

    # GET /translations
    # GET /translations.json
    before_filter :authenticate_translator!
    load_and_authorize_resource :translation, :class => TolkEngine::Translation

    def index
      @locale = Locale.find_by_id(params[:locale_id])
      if @locale
        @translations = @locale.translations
      else
        @translations = Translation.all
      end

      # @translations = @translations.order('text') if !@translations.empty?

      if !Translation.all.empty?
        @latest_translation_load_date = Translation.maximum("created_at").to_date
      end
      @update_dates = @translations.map {|translation| translation.updated_at.to_date}.uniq

      @relevant_phrase_text = create_phrase_translation_table(@translations)
      @yml_hash = TolkEngine::TranslationsManager.create_translation_hash(@translations)

      standard_respond_to(@translations)
    end

    # GET /translations/1
    # GET /translations/1.json
    def show
      @relevant_locale = @translation.locale
      @relevant_locale_name = @relevant_locale.name


      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @translation }
      end
    end

    # GET /translations/new
    # GET /translations/new.json
    def new
      @corresponding_phrase = Phrase.find(params[:phrase_id])
      @translation = @corresponding_phrase.translations.build(params[:translation])
      @translation.phrase_id = @corresponding_phrase.id

      standard_respond_to(@translation)
    end

    # GET /translations/1/edit
    def edit
      @translations_list = Translation.all

      @translations_list.each do |translation|
        if translation.locale_id == 1 && translation.phrase_id == @translation.phrase_id
          @primary_translation = translation.text
        end
      end

    end

    # POST /translations
    # POST /translations.json
    def create
      @corresponding_phrase = Phrase.find(params[:phrase_id])
      @translation = @corresponding_phrase.translations.build(params[:translation])
      @translation = add_current_translator_information(@translation)

      create_respond_to(@translation)
    end

    # PUT /translations/1
    # PUT /translations/1.json
    def update
      @translation.translator_id = current_translator.id
      @translation.locale_id = current_translator.locale_id
      @translation.needed_update_flag_update

      next_translation_path = next_path(@translation)

      update_respond_to(@translation, params[:translation], locale_translations_path(current_translator.locale))
    end

    # DELETE /translations/1
    # DELETE /translations/1.json
    def destroy
      @translation.destroy

      destroy_respond_to
    end

    private
    def add_current_translator_information(translation)
      translation.author = current_translator.id
      translation.locale_id = current_translator.locale_id
    end

    def next_path(current_translation)
      locale = current_translator.locale
      @locale_translations = locale.translations
      @locale_translations_needed = @locale_translations.where(:needed_update => 1)
      @locale_translations_needed = @locale_translations_needed.where("id != ?", current_translation.id )
      @next_translation = @locale_translations_needed.first

      if @next_translation.nil?
        locale_translations_path(@translation.locale)
      else
        edit_translation_path(@next_translation)
      end
    end

    def create_update_date_table(translations)
      update_date = {}
      translations.each do |translation|
        update_date[translation.updated_at.to_date] = translation.updated_at.to_date
      end
      update_date
    end

    def create_create_date_table(translations)
      create_date = {}
      translations.each do |translation|
        if translation.need_updated? && translation.created_at.to_date != @latest_translation_load_date
          create_date[translation.created_at.to_date] = translation.created_at.to_date
        end
      end
      create_date
    end
  end
end

app/controllers/tolk_engine/translations_in_line_controller.rb
module TolkEngine
  class TranslationsInLineController < TolkEngine::ApplicationController
    before_filter :authenticate_translator!
    load_and_authorize_resource :translation, :class => TolkEngine::Translation

    def index
      @locale = current_translator.locale
      if @locale && !current_translator.locale.is_primary?
        @translations = @locale.translations.translation_needed
      else
        @translations = @locale.translations
      end
      primary_locale = Locale.primary_locale
      @first_locale_translations = primary_locale.translations
      @corresponding_phrase = create_phrase_translation_table(@translations)
    end

    def edit
      @corresponding_phrase = create_phrase_translation_table(@translations)
    end

    def update
      Translation.update(params[:translations].keys, params[:translations].values)
      flash[:notice] = "Translations updated"
      redirect_to root_path
    end

    def create
      @corresponding_translation = Translation.find(params[:translation_id])
      create_respond_to(@corresponding_translation)
    end
  end
end

app/controllers/tolk_engine/translators_controller.rb
module TolkEngine
  class TranslatorsController < TolkEngine::ApplicationController
    # GET /translators
    # GET /translators.json
     layout "tolk_engine/layouts/tolk_engine"

    before_filter :authenticate_translator!
    load_and_authorize_resource :translator, :class => Translator

    def index
      @locales = Locale.all

      standard_respond_to(@translators)
    end

    # GET /translators/1
    # GET /translators/1.json
    def show
      standard_respond_to(@translator)
    end

    # GET /translators/new
    # GET /translators/new.json
    def new
      @translator = Translator.new
      @locales = Locale.all

      standard_respond_to(@translator)
    end

    # GET /translators/1/edit
    def edit
      @locales = Locale.all
    end

    # POST /translators
    # POST /translators.json
    def create
      @locales = Locale.all

      create_respond_to(@translator)
    end

    # PUT /translators/1
    # PUT /translators/1.json
    def update
      update_respond_to(@translator, params[:translator])
    end

    # DELETE /translators/1
    # DELETE /translators/1.json
    def destroy
      @translator.destroy
      destroy_respond_to
    end
  end
end

app/controllers/tolk_engine/yml_files_controller.rb
module TolkEngine
  class YmlFilesController < TolkEngine::ApplicationController

  	def index
  		@locale = Locale.find_by_id(params[:locale_id])
      if @locale
        @translations = @locale.translations
      else
        @translations = Translation.all
      end
      @yml_hash = {}
      @translation_hash = TolkEngine::TranslationsManager.create_translation_hash(@translations)
      @yml_hash = TolkEngine::TranslationsManager.hash_to_export(@translation_hash, "", " ", "\n")
      if !@yml_hash.blank?
        TolkEngine::YmlLoader.export_hash_to_yaml_locale(@yml_hash, @locale)
      end
      respond_to do |format|
     		if !request.env["HTTP_REFERER"].blank?
     			format.html { redirect_to :back }
     		else
     			format.html { redirect_to root_path }
     		end
  		end
  	end
  end
end

app/views/tolk_engine/translations/_form.html.haml
= form_for [@corresponding_phrase, @translation] do |f|
  - if @translation.errors.any?
    #error_explanation
      %h2
        = pluralize(@translation.errors.count, "error")
        prohibited this translation from being saved:
      %ul
        - @translation.errors.full_messages.each do |msg|
          %li= msg
  .span4.autoresize
    %h3= t("traduction pour »")
    %p= @primary_translation
  .field
    = f.text_area :text
  .actions
    = f.submit

app/views/tolk_engine/translations/_translation_row.html.haml
%td

- if @relevant_phrase_text[translation.phrase_id].blank?
  %td= "-"
- else
  %td
    = @relevant_phrase_text[translation.phrase_id]
    .less-important= translation.phrase.yaml_path

%td= translation.text

- if !translation.need_updated?
  %td= translation.created_at.to_date
  %td= translation.updated_at.to_date
- else
  %td= translation.created_at.to_date
  %td= "-"

- if (can? :update, translation)
  %td= link_to 'Edit', edit_translation_path(translation), :class => 'btn btn-warning'

app/views/tolk_engine/translations/edit.html.haml
.center#home
  .row
    .span9
      .header
        %h1 Editing translation
  .row
    .span9
      = form_for [@corresponding_phrase, @translation] do |f|
        - if @translation.errors.any?
          #error_explanation
            %h2
              = pluralize(@translation.errors.count, "error")
              prohibited this translation from being saved:
            %ul
              - @translation.errors.full_messages.each do |msg|
                %li= msg
        %p
          Translation for : "
          = @primary_translation
          "
        .field
          = f.text_area :text
        .actions
          = f.submit
  .row
    .span9
      = link_to 'Show', @translation, :class => 'btn btn-info'
      = link_to 'Back', locale_translations_path(current_translator.locale), :class => 'btn btn-warning'

app/views/tolk_engine/translations/index.html.haml
.alert.alert-grey
  .page-header
    %h1= "These translations are refering to the folowing langage : #{@locales_name[current_translator.locale.name]}."
    .offset02= "De plus, les traductions sont effectuées par #{current_translator.name}"

%table.table.table-condensed.my_tab
  %tr.font-size16
    %td
    %td
      %strong
        .span-text English
    %td
      %strong
        .span-text Translation
    %td
      %strong
        .span2 Creation date
    %td
      %strong
        .span2 Update date
    %td
      %strong
        .span1.offser05 Edit

  - @update_dates.sort.each do |date|
    - flag = 0
    - @translations.each do |translation|
      - if translation.need_updated? && translation.created_at.to_date != @latest_translation_load_date && translation.created_at.to_date.to_s == date.to_s
        - if flag <= 0
          %tr.alert.alert-error
            %td{:colspan => "6"}
              %i.icon-exclamation-sign
              %i.icon-exclamation-sign
              %strong.font-size16.black-shadow
                Still to do since
                = date
          - flag = 1
        %tr.alert.alert-error#font-size14
          = render 'translation_row', :translation => translation
    - @translations.each do |translation|
      - if translation.need_updated? && translation.created_at.to_date == @latest_translation_load_date && @latest_translation_load_date.to_s == date.to_s
        - if flag <= 1
          %tr.alert.alert-warning
            %td{:colspan => "6"}
              %i.icon-question-sign
              %i.icon-exclamation-sign
                %strong.font-size16.black-shadow
                  New to translate since
                  = @latest_translation_load_date
          - flag = 2
        %tr.alert.alert-warning#font-size14
          = render 'translation_row', :translation => translation
    - @translations.each do |translation|
      - if !translation.need_updated? && translation.updated_at.to_date.to_s == date.to_s
        - if flag <= 2
          %tr.alert.alert-success
            %td{:colspan => "6"}
              %i.icon-ok-sign
                %strong.font-size16.black-shadow
                  = t('what_has_been_done_on')
                  = date
          - flag = 3
        %tr.alert.alert-success#font-size14
          = render 'translation_row', :translation => translation

app/views/tolk_engine/translations/new.html.haml
%h1 New translation
= render 'form'
= link_to 'Back', translations_path

app/views/tolk_engine/translations/show.html.haml
%p#notice= notice
%p
  %b Text:
  = @translation.text
%p
  %b Author:
  = @translation.translator_id
%p
  %b Original text:
  - primary_locale = Locale.primary_locale
  %b= primary_locale.translations.where(:phrase_id => @translation.phrase_id).first.text
%p
  %b Locale:
  = @relevant_locale_name
%p
  %b statut:
  = @translation.needed_update

= link_to 'Edit', edit_translation_path(@translation)
|
\#{link_to 'Back', locale_translations_path(@translation.locale)}